import { Inter } from "next/font/google";
import SiderBar from "./Components/SiderBar";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html className="bg-white h-full" lang="en">
        <body className="w-full h-full" suppressHydrationWarning={true}>
          {children}
        </body>
      </html>
    </Providers>
  );
}
